title: "light.gg Frequently Asked Questions"
remote_theme: pmarsceill/just-the-docs
# Aux links for the upper right navigation
aux_links:
  "light.gg":
    - "//light.gg"
footer_content: "Copyright &copy; light.gg"
color_scheme: "dark"
ga_tracking: UA-107713767-1
